FROM node:22-alpine AS build
WORKDIR /app

ARG VITE_URL_BACKEND_INTERNAL
ENV VITE_URL_BACKEND_INTERNAL=$VITE_URL_BACKEND_INTERNAL
ARG VITE_URL_BACKEND_EXTERNAL
ENV VITE_URL_BACKEND_EXTERNAL=$VITE_URL_BACKEND_EXTERNAL

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80