services:
  backend:
    image: ghcr.io/briiiqtt/short-url-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shorturl
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=cache
    depends_on:
      db:
        condition: service_healthy
    networks:
        - inter-net
        - bombs

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=shorturl
      - TZ=Asia/Seoul
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d shorturl']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - inter-net

  cache:
    image: redis
    volumes:
      - cache-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - inter-net

  frontend:
    image: ghcr.io/briiiqtt/short-url-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_URL_BACKEND_INTERNAL=http://s.bombs.kr
        - VITE_URL_BACKEND_EXTERNAL=http://s.bombs.kr
    environment:
      - NODE_ENV=produce
    networks:
      - bombs

volumes:
  db-data:
  cache-data:

networks:
  inter-net:
  bombs:
    external: true