services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - gradle-cache:/root/.gradle
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    command: ./gradlew bootRun

  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: shorturl
      TZ: Asia/Seoul
    volumes:
      - db-data:/container/path:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shorturl"]
      interval: 10s
      timeout: 5s
      retries: 5

    
volumes:
  gradle-cache:
  db-data: