services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - gradle-cache:/root/.gradle
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    command: ./gradlew bootRun
    networks:
      - internal-net
      - external-net

  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: shorturl
      TZ: Asia/Seoul
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d shorturl"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal-net

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
          - VITE_URL_BACKEND_INTERNAL=http://backend:8080
          - VITE_URL_BACKEND_EXTERNAL=http://127.0.0.1:8080
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - external-net

    
volumes:
  gradle-cache:
  db-data:
  redis-data:

networks:
  internal-net:
  external-net: