FROM eclipse-temurin:21-jdk-alpine AS build

WORKDIR /app

COPY gradlew build.gradle.kts settings.gradle.kts ./
COPY gradle gradle/
COPY src src/

RUN ./gradlew bootJar && cp build/libs/*.jar app.jar

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build /app/app.jar .

ENTRYPOINT [ "java", "-jar", "app.jar" ]